config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "home#index"
  resources :users do 
  	resources :posts do
      member do 
        put "apply", to: "posts#apply"
      end
    end
  end

  get 'cities/:state', to: 'application#cities'
  	
  get "/sign_up" => "users#new", as: "sign_up"
  get "/sign_in" => "sessions#new", as: "sign_in"
  post "/login" => "sessions#create", as: "login"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/search" => "home#search"

  get "/*path" => "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	acts_as_votable
	enum status: [:available, :expired]
	belongs_to :user
	validates :name, presence: true, length: { minimum: 3 }
	validates :description, presence: true
	validates :date, presence: true, on: :create;
	validates :address, presence: true
	validates :city, presence: true, on: :create;
	validates :state, presence: true, on: :create;
	validates :country, presence: true, on: :create;
	validates :zipcode, presence: true, on: :create;
	
end

app/models/user.rb
class User < ApplicationRecord
	acts_as_voter
	has_secure_password

	enum role: [:recruiter, :jobseeker]
	has_many :posts, dependent: :destroy
	validates :name, presence: true, length: { minimum: 3 }
	validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
	validates :password, presence: true, on: :create;
	validates :role, presence: true, on: :create;
	validates_confirmation_of :password, on: :create;

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #before_action :block_array_parameters

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def logged_in?
    !current_user.nil?
  end
  helper_method :logged_in?

  def sign_in(user)
    session[:user_id] = user.id
  end

  def cities
    render json: CS.cities(params[:state], :my).to_json
  end
  
      def block_array_parameters
      params.each do |key, value|
        if key != 'controller' && key != 'action'
          if params[key].is_a? Array
		    key = key.gsub(/\W/, "")
            render status: 403, json: JSON.pretty_generate({ error: "`#{key}` parameter can't be an array." })
          end
        end
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@post = Post.includes(:user).where(status: 0).order(created_at: :desc).page params[:page]
	end

	def search
		if params[:search] != ""
           @results = Post.where('lower(name) iLIKE ?', "%#{params[:search]}%").order(:created_at)
           @user = User.where('lower(name) iLIKE ?', "%#{params[:search]}%").order(:created_at)
       end  
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy, :apply]
	before_action :post_owner_check, only: [:edit, :update, :destroy]
	before_action :logged_in_check, :recruiter_check, only: [:new] 

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			flash[:success] = "Job post is created successfully!"
			redirect_to user_post_path(current_user.id, @post.id)
		else
			# flash[:notice] = "Something went wrong, please try again. (Please fill in all the fields)"
			respond_to do |format|
          		format.html { redirect_to new_user_post_path(current_user.id) }
          		format.js
        	end
			
		end
	end

	def show
	end

	def edit
	end

	def update
		@post.update(post_params)
		flash[:success] = "Job post has been updated successfully!"
		redirect_to user_post_path(@post.user_id, @post.id)
		@post.save
	end

	def destroy
		@post.destroy
		flash[:success] = "Job post has been deleted successfully!"
		redirect_to user_path(current_user.id)
	end

	def apply
		if (current_user.voted_for? @post) == false
			@post.upvote_by current_user
			flash[:success] = "Job application submitted successfully!"
			redirect_to user_post_path(@post.user_id, @post.id)
		elsif (current_user.voted_for? @post) == true
			respond_to do |format|
          		format.html { redirect_to user_post_path(@post.user_id, @post.id) }
          		format.js
        	end
        end
	end

	private

	def find_post 
		if @post = Post.find_by(id: params[:id])
			return @post
		else
			redirect_to "/", alert: "Post does not exist!"
		end
	end

	def logged_in_check
    	if current_user.nil?
    		redirect_to "/", alert: "Log in or Sign up first!"
    	end
  	end

  	def recruiter_check
  		if current_user.jobseeker?
  			redirect_to "/", alert: "Only recruiter has the access!"
  		end
  	end

	def post_owner_check
		if logged_in? and current_user.id != @post.user_id
			redirect_to "/", alert: "Only the post's owner has the access!"
		elsif !logged_in?
			redirect_to "/", alert: "Only the post's owner has the access!"
		end
	end

	def post_params
		params.require(:post).permit(:name, :description, :status, :user_id, :country, :zipcode, :state, :city, :date, :address)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	    if logged_in?
	      redirect_to "/", notice: "You already signed in!"
	    end
	end

	def create
		user = User.find_by(email: params[:email])
	    	if user && user.authenticate(params[:password])
		      	session[:user_id] = user.id
		      	flash[:notice] = "Welcome back, " + user.name + "!"
		      	redirect_to '/'
	      	else
	    	 	# flash[:notice] = "Email and password mismatched. Try again."
	       		respond_to do |format|
	          		format.html { redirect_to '/sign_in' }
	          		format.js
	        	end
      		end
	end

	def destroy
		session[:user_id] = nil
		flash[:notice] = "Logged out sucessfuly. We will miss you ;("
    	redirect_to '/'
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :find_user, only: [:show, :edit, :update]
	before_action :current_user_check, only: [:edit, :update]

	def new
		if !logged_in?
			@user = User.new
		elsif logged_in?
			redirect_to "/", notice: "You already signed up!"
		end
	end

	def create
		user = User.new(user_params)
  		if user.save
    		session[:user_id] = user.id
    		flash[:success] = "Signed up successfully"
    		redirect_to '/'
  		else
  			# flash[:notice] = "Password confirmation doesn't match password"
  			respond_to do |format|
          		format.html { redirect_to '/sign_up' }
          		format.js 
        	end
    		
  		end
	end

	def show
		@post = Post.where(user_id: @user.id).order(created_at: :desc).page params[:page]
	end

	def edit
	end

	def update
		@user.update(user_params)
		flash[:success] = "Profile has been updated successfully!"
		redirect_to @user
	end

	private

	def find_user
		if @user = User.find_by(id: params[:id])
			return @user  
		else
			redirect_to "/", alert: "User does not exist!"
		end
	end

	def current_user_check
		if logged_in? and current_user.id != @user.id 
    		redirect_to "/", alert: "Hold it right there! You don't have the permission to access!"
    	elsif !logged_in?
    		redirect_to "/", alert: "Hold it right there! You don't have the permission to access!"
    	end
  	end

	def user_params
  		params.require(:user).permit(:name, :email, :role, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
		case level
	        when 'notice' then "alert alert-info"
	        when 'success' then "alert alert-success"
	        when 'error' then "alert alert-warning"
	        when 'alert' then "alert alert-danger"
	    end
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="container padding">
	<div class="row">
		<h1>Welcome to Rails bug test!</h1>
	</div>
	<br>
	<div class="row">
		<% if @post.size != 0 %>
		
		<% @post.each do |post| %>
			
			<div class="col-md-12">
				<h3><%= link_to post.name, user_post_path(post.user_id, post.id) %></h3>
				<p>Created by: <%= link_to post.user.name, user_path(post.user.id) %> on <%= post.date %></p>			
				<hr>
			</div>
		<% end %>
		
	<% else %>
		<h3>No job post created yet</h3>
	<% end %>

	<p><%= paginate @post %></p>
	</div>
</div>

app/views/home/search.html.erb
<div class="container">
	<h3>Results for: <%= params[:search] %></h3>
	<br>
	<ul>

		<% if !@results.nil? %>
		<% @results.each do |result| %>
			<li>
				<h4><%= link_to result.name, user_post_path(result.user.id, result.id) %></h4>
				<p>Created by: <%= link_to result.user.name, user_path(result.user_id) %> on <%= result.date %></p>
			</li>
				
		<% end %>
		<% end %>
		<% if !@user.nil? %>
		<% @user.each do |user| %>
			<li>
				<h4><%= link_to user.name, user_path(user.id) %></h4>
				<p>Role: <%= user.role %></p>
			</li>
		<% end %>
		<% end %>
		<% if @user.nil? and @results.nil? %>
			<h3>Uh Oh, nothing's found ;(</h3>
		<% elsif @user.size == 0 and @results.size == 0 %>
			<h3>Uh Oh, nothing's found ;(</h3>
		<% end %>
	</ul>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Rails Bug Hub</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <div id="search-bar", class="navbar-left navbar-form">
      <div class="form-group">
        <%= form_tag '/search', method: :get do %>
          <%= text_field_tag :search, params[:search], class:"form-control" %>
          <%= submit_tag "Search", class:"btn btn-default " %>
        <% end %>
      </div>
      </div>
      <% if !logged_in? %>
        <li><%= link_to "Sign up", sign_up_path %></li>
        <li><%= link_to "Sign in", sign_in_path %></li>
      <% elsif logged_in? %>
        <% if current_user.recruiter? %>
          <li><%= link_to "Create Job Post", new_user_post_path(current_user.id) %></li>
        <% end %>
        <li><%= link_to current_user.name, user_path(current_user.id) %></li>
        <li><%= link_to "Sign out", sign_out_path, method: :delete %></li>
      <% end %>
    </ul>
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Bug Hub</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<%= render partial: "/layouts/navbar" %>

  	<div id="flash">
    	<% flash.each do |key, value| -%>
      		<div id="flash_<%= key %>", class="<%= flash_class(key) %>"><%=h value %></div>
    	<% end %>
  	</div>
  	
    <%= yield %>
  </body>
</html>

app/views/posts/apply.js.erb
$("<h4 class='text-danger'>You already applied for this job!</h4>").hide().appendTo("#apply-btn").fadeIn(999);
$("h4").remove();
$("<h4 class='text-danger'>You already applied for this job!</h4>").hide().appendTo("#apply-btn").fadeIn(999);

app/views/posts/create.js.erb
$("<h4 class='bg-danger'>Please make sure to fill in all the 'required' fields. Try again.</h4>").hide().appendTo("h1").fadeIn(999);
$("h4").remove();
$("<h4 class='bg-danger'>Please make sure to fill in all the 'required' fields. Try again.</h4>").hide().appendTo("h1").fadeIn(999);

app/views/posts/edit.html.erb
<div class="container">
	<h1>Edit job post:</h1>

	<%= form_for @post, url: user_post_path(current_user.id), method: :put do |form| %>
		<%= form.hidden_field :user_id, value:current_user.id %>

		<div class="form-group">
			<%= form.label :status, "Availability" %>
        	<%= form.select :status, options_for_select([:available, :expired], :available), {}, class:"form-control custom-select" %>
        </div>

		<div class="form-group">
			<%= form.label :name %>
			<%= form.text_field :name, class:"form-control" %>
		</div>

		<div class="form-group">
			<%= form.label :description %>
			<%= form.text_area :description, class:"form-control", rows: "8"%>
		</div>

	  	<%= form.submit "Submit", class:"btn btn-primary align-center" %>
	<% end %>
</div>

app/views/posts/new.html.erb
<div class="container">
	<h1>Create new job post!</h1>

	<%= form_for @post, url: user_posts_path(current_user.id), method: :post, remote: true do |form| %>
		<%= form.hidden_field :user_id, value:current_user.id %>
		<div class="form-group">
			<%= form.label :name %>
			<%= form.text_field :name, class:"form-control" %>
		</div>

		<div class="form-group">
			<%= form.label :description %>
			<%= form.text_area :description, class:"form-control", rows: "8"%>
		</div>

		<div class="form-group" id="datepicker">
      		<%= form.label :date %>
      		<%= form.text_field :date, data:{provide:"datepicker", date_format: 'yyyy-mm-dd', turbolinks: false }, class:"form-control"%>
    	</div>

    	<div class="form-group">
      		<%= form.label :address %>
      		<%= form.text_field :address, class:"form-control", rows:"5"%>
    	</div>

	    <div class="form-group">
	    	<%= form.label :country %>
	    	<select id="country" name="post[country]" class="form-control form-control-small" required>
	      	<option value="" selected>Select Your Country</option>
	      	<% CS.countries.each do |key, value| %>
	        	<option value="<%= key %>"><%= value%></option>
	     	<% end %>
	    	</select>
	    </div>

	    <div class="form-group">
	    	<%= form.label :state %>
	    	<select id="states-of-country" name="post[state]" class="form-control form-control-small" required>
	        <option id="no-state" value="" selected>Select Your State</option>
	      	<% CS.states(:my).each do |key, value| %>
	        	<option value="<%= value %>" id="<%= key %>"><%= value %></option>
	      	<% end %>
	    	</select>
	    </div>

	    <div class="form-group">
	      <%= form.label :city %>
	      <select id="cities-of-state" name="post[city]" class="form-control form-control-small" required>
	      	<option value="" selected>Select Your City</option>
	      </select>
	    </div>

	    <script type="text/javascript">

	      $(document).on('change', '#states-of-country', function(e) {
	        var cities_of_state, input_state, state;
	        input_state = $(this);
	        cities_of_state = $('#cities-of-state');
	        state = this.options[e.target.selectedIndex].id;
	        if (state === 'no-state') {
	          return cities_of_state.html('');
	        } else {
	          $.ajax({
	            url: '/cities/' + $(this).children(':selected').attr('id'),
	            success: function(data) {
	              var opt;
	              opt = '<option value="" selected>Select Your City</option>';
	              if (data.length === 0) {

	              } else {
	                data.forEach(function(i) {
	                  opt += '<option value="' + i + '">' + i + '</option>';
	                });
	                cities_of_state.html(opt);
	              }
	            }
	          });
	        }
	      });
	    </script>

	    <div class="form-group">
	      <%= form.label :zipcode %>
	      <%= form.number_field :zipcode, class:"form-control", rows:"5" %>
	    </div>

	  	<%= form.submit "Submit", class:"btn btn-primary align-center" %>
	<% end %>
</div>

app/views/posts/show.html.erb
<div class="container padding">
	<h1><%= @post.name %></h1>
	<p>Created by: <%= link_to @post.user.name, user_path(@post.user.id) %> on <%= @post.date %></p>
	<p>Status: <%= @post.status %></p>
	<% if logged_in? and current_user.voted_for? @post %>
		<p class="text-success">You have applied for this job.</p>
	<% else %>
		<p class="text-success"><%= @post.get_upvotes.size %> people has applied for this job.</p>
	<% end %>
	<% if logged_in? and current_user.id == @post.user_id%>
		<%= link_to "Edit", edit_user_post_path(current_user.id, @post.id), class:"btn btn-default" %>
		<%= link_to "Delete", user_post_path(current_user.id, @post.id), method: :delete, data: { confirm: 'Sure? This action cannot be reverted!' }, class:"btn btn-danger" %>
	<% end %>
	<hr>
	<h3>Description:</h3>
	<p class="textarea"><%= @post.description %></p>
	<br>
	<h3>Location:</h3>
	<p><%= @post.address %>, <%= @post.zipcode %> <%= @post.city %>, <%= @post.state %>, <%= @post.country%>.</p>
	<br>
	<% if logged_in? and current_user.jobseeker? %>
		<%= link_to "Apply now!", apply_user_post_path(current_user.id, @post.id), method: :put, remote: true, class:"btn btn-success" %>
		<div id="apply-btn"></div>
	<% elsif !logged_in? %>
		<%= link_to "Apply now!", "", class:"btn btn-success disabled" %>
		<p>Please sign up/sign in to apply for this job!</p>
	<% end %>
	<hr>
	<% if logged_in? and current_user.id == @post.user_id %>
		<% if @post.votes_for.up.by_type(User).voters.size != 0 %>
			<h2>Applicants:</h2><br>
				<% @post.votes_for.up.by_type(User).voters.each do |applicant| %>
					<h4>- <%= link_to applicant.name, user_path(applicant.id) %></h4>
					<hr>
				<% end %>
		<% elsif @post.votes_for.up.by_type(User).voters.size == 0 %>
			<h4>No application yet!</h4>
		<% end %>
	<% end %>

</div>

app/views/users/create.js.erb
$("<h4 class='bg-danger'>Please make sure everything is filled in correctly and try again ;)</h4>").hide().appendTo("h1").fadeIn(999);
$("h4").remove();
$("<h4 class='bg-danger'>Please make sure everything is filled in correctly and try again ;)</h4>").hide().appendTo("h1").fadeIn(999);

app/views/users/edit.html.erb
<div class="container">
	<h1>Edit profile:</h1>

	<%= form_for @user do |form| %>
		<div class="form-group">
			<%= form.label :name %>
			<%= form.text_field :name, class:"form-control" %>
		</div>

		<div class="form-group">
			<%= form.label :email %>
			<%= form.text_field :email, class:"form-control" %>
		</div>

		<div class="form-group">
			<%= form.label :password %>
	 		<%= form.password_field :password, class:"form-control" %>
	 	</div>
	 	<div class="form-group">
			<%= form.label :password_confirmation, "Confirm password" %>
	  		<%= form.password_field :password_confirmation, class:"form-control" %>
	  	</div>

	  	<%= form.submit "Update", class:"btn btn-primary align-center" %>
	<% end %>
</div>

app/views/users/new.html.erb
<div class="container margin-top padding-btm">
	<div class="col-md-6 col-md-offset-3">
		<h1>Signup!</h1>

		<%= form_for @user, remote: true do |form| %>
			<div class="form-group">
				<%= form.label :name %>
				<%= form.text_field :name, class:"form-control" %>
			</div>

			<div class="form-group">
				<%= form.label :email %>
				<%= form.text_field :email, class:"form-control" %>
			</div>
			<div class="form-group">
				<%= form.label :role, "Sign up as?" %>
	        	<%= form.select :role, options_for_select([:recruiter, :jobseeker], :recruiter), {}, class:"form-control custom-select" %>
	        </div>

			<div class="form-group">
				<%= form.label :password %>
		 		<%= form.password_field :password, class:"form-control" %>
		 	</div>
		 	<div class="form-group">
				<%= form.label :password_confirmation, "Confirm password" %>
		  		<%= form.password_field :password_confirmation, class:"form-control" %>
		  	</div>

		  	<%= form.submit "Submit", class:"btn btn-primary align-center" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<div class="container padding">
	<h1>Welcome to <%= @user.name %>'s profile (<%= @user.role.capitalize %>)</h1>
	<br>
	<% if logged_in? %>
		<%= link_to "Edit", edit_user_path(@user.id), class:"btn btn-default" %>
	<% end %>
	<hr>
	<h4>Name: <%= @user.name %></h4>
	<h4>Email: <%= @user.email %></h4>
	<% if logged_in? and @user.recruiter? %>
		<% if @user.id == current_user.id %>
			<h2>Your job posts:</h2>
			<br>
			<% if current_user.posts.size != 0 %>
				<% @post.each do |post| %>	
					<h4><%= link_to post.name, user_post_path(@user.id, post.id) %></h4>
					<p>Created on: <%= post.date %></p>
					<hr>
				<% end %>
				<p><%= paginate @post %></p>
			<% else %>
				<h4>You have no job post yet, <%= link_to "create one now!", new_user_post_path(current_user.id) %>
			<% end %>
		<% elsif @user.id != current_user.id and @user.recruiter? %>
			<h2><%= @user.name %>'s posts:</h2>
			<br>
			<% if @user.posts.size != 0 %>
				<% @post.each do |post| %>	
					<h4><%= link_to post.name, user_post_path(@user.id, post.id) %></h4>
					<p>Created on: <%= post.date %></p>
					<hr>
				<% end %>
				<p><%= paginate @post %></p>
			<% else %>
				<h4><%= @user.name %> has no job post yet</h4>
			<% end %>
		<% end %>
	<% elsif @user.recruiter? %>
		<h2><%= @user.name %>'s posts:</h2>
		<br>
		<% if @user.posts.size != 0 %>
			<% @post.each do |post| %>	
				<h4><%= link_to post.name, user_post_path(@user.id, post.id) %></h4>
				<p>Created on: <%= post.date %></p>
				<hr>
			<% end %>
			<p><%= paginate @post %></p>
		<% else %>
			<h4><%= @user.name %> has no job post yet</h4>
			<hr>
		<% end %>
	<% end %>
	<% if logged_in? and current_user.id == @user.id %>
		<% if current_user.jobseeker? %>
			<% if current_user.find_up_voted_items.size != 0 %>
				<h2>Your application history:</h2><br>
				<% current_user.find_up_voted_items.each do |application| %>
					<h4>- <%= link_to application.name, user_post_path(application.user_id, application.id) %></h4>
					<hr>
				<% end %>
			<% elsif current_user.find_up_voted_items.size == 0 %>
				<h4>You have not applied for jobs yet!</h4>
				<%= link_to "Start apply here!", root_path, class:"btn btn-success" %>
			<% end %>
		<% end %>
	<% end %>
</div>